apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: gateway-jwt-policy
  namespace: istio-system
spec:
  targets:
    - name: istio-ingressgateway
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "http://localhost:8080/auth/realms/istio"
        jwks_uri: "http://keycloak/auth/realms/istio/protocol/openid-connect/certs"
        trigger_rules:
          - included_paths:
              - prefix: /offer/
              - prefix: /loan/
              - prefix: /user/
  principalBinding: USE_ORIGIN
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    services:
      - "istio-ingressgateway.istio-system.svc.cluster.local"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: anonymous-role
  namespace: istio-system
spec:
  rules:
    - paths:
        - "/offer-frontend/*"
        - "/loan-frontend/*"
        - "/loan/error/*"
        - "/loan/info/*"
        - "/user/fullName*"
        - "/borrowerLoan/*"
      methods:
        - "GET"
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-anonymous
  namespace: istio-system
spec:
  subjects:
    - user: "*"
  roleRef:
    kind: ServiceRole
    name: anonymous-role
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: borrower-role
  namespace: istio-system
spec:
  rules:
    - paths:
        - "/offer/*"
      methods:
        - "POST"
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-borrower
  namespace: istio-system
spec:
  subjects:
    - properties:
        request.auth.claims[groups]: "/borrower"
  roleRef:
    kind: ServiceRole
    name: borrower-role
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
    - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
