server:
  port: 8078
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: loan-app

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  topic:
    offer-events: ${KAFKA_TOPIC_OFFER}
    loan-events: ${KAFKA_TOPIC_LOAN}
    loan-error-events: ${KAFKA_TOPIC_LOAN_ERROR}
    instalment-events: ${KAFKA_TOPIC_INSTALMENT}
    instalment-error-events: ${KAFKA_TOPIC_INSTALMENT_ERROR}
    product-events: ${KAFKA_TOPIC_PRODUCT}
    product-error-events: ${KAFKA_TOPIC_PRODUCT_ERROR}


