version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_VERSION: "2.12-2.2.1"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "product-messages:2:1,product-error-messages:2:1,loan-messages:2:1,loan-error-messages:2:1,instalment-messages:2:1,instalment-error-messages:2:1,offer-messages:2:1,offer-error-messages:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
